2018-02-13T00:05:40.6688862+11:00 0HLBI358JCCNE:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44388/   (ca22a1cb)
2018-02-13T00:05:41.0112648+11:00 0HLBI358JCCNE:00000001 [INF] Executing action method "DOMS.WebApp.Controllers.HomeController.Index (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:05:41.0521774+11:00 0HLBI358JCCNE:00000001 [INF] Executing RedirectResult, redirecting to "/Account/Login". (d98d540e)
2018-02-13T00:05:41.0636595+11:00 0HLBI358JCCNE:00000001 [INF] Executed action "DOMS.WebApp.Controllers.HomeController.Index (DOMS.WebApp)" in 67.729ms (afa2e885)
2018-02-13T00:05:41.0863945+11:00 0HLBI358JCCNE:00000001 [INF] Request finished in 470.4418ms 302  (791a596a)
2018-02-13T00:05:41.1049628+11:00 0HLBI358JCCNE:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Account/Login   (ca22a1cb)
2018-02-13T00:05:41.4140369+11:00 0HLBI358JCCNE:00000002 [INF] Executing action method "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:05:41.4479822+11:00 0HLBI358JCCNE:00000002 [INF] AuthenticationScheme: "Identity.External" signed out. (d3f50c8d)
2018-02-13T00:05:47.7947277+11:00 0HLBI358JCCNE:00000002 [INF] Executing ViewResult, running view at path "/Views/Account/Login.cshtml". (9707eebe)
2018-02-13T00:05:48.0907157+11:00 0HLBI358JCCNE:00000002 [INF] Executed action "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" in 6918.0866ms (afa2e885)
2018-02-13T00:05:48.1141172+11:00 0HLBI358JCCNE:00000002 [INF] Request finished in 6994.968ms 200 text/html; charset=utf-8 (791a596a)
2018-02-13T00:05:49.8534189+11:00 0HLBI358JCCNE:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44388/Account/Login application/x-www-form-urlencoded 246 (ca22a1cb)
2018-02-13T00:05:49.9275065+11:00 0HLBI358JCCNE:00000003 [INF] Executing action method "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" with arguments (["DOMS.Model.ViewModels.AccountViewModels.LoginViewModel", ""]) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:05:50.3524095+11:00 0HLBI358JCCNE:00000003 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:05:50.7734604+11:00 0HLBI358JCCNE:00000003 [INF] Executed DbCommand ("55"ms) [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0" (0723d8ff)
2018-02-13T00:05:51.0188555+11:00 0HLBI358JCCNE:00000003 [INF] Executed DbCommand ("21"ms) [Parameters=["@__user_Id_0='?' (Size = 450)"], CommandType='Text', CommandTimeout='30']"
""SELECT [uc].[Id], [uc].[ClaimType], [uc].[ClaimValue], [uc].[UserId]
FROM [AspNetUserClaims] AS [uc]
WHERE [uc].[UserId] = @__user_Id_0" (0723d8ff)
2018-02-13T00:05:51.1543543+11:00 0HLBI358JCCNE:00000003 [INF] Executed DbCommand ("7"ms) [Parameters=["@__userId_0='?' (Size = 450)"], CommandType='Text', CommandTimeout='30']"
""SELECT [role].[Name]
FROM [AspNetUserRoles] AS [userRole]
INNER JOIN [AspNetRoles] AS [role] ON [userRole].[RoleId] = [role].[Id]
WHERE [userRole].[UserId] = @__userId_0" (0723d8ff)
2018-02-13T00:05:51.1834340+11:00 0HLBI358JCCNE:00000003 [INF] AuthenticationScheme: "Identity.Application" signed in. (c66dd7e7)
2018-02-13T00:05:51.1932477+11:00 0HLBI358JCCNE:00000003 [INF] User logged in. (fdce0db4)
2018-02-13T00:05:51.2087666+11:00 0HLBI358JCCNE:00000003 [INF] Executing RedirectResult, redirecting to "/Home/Dashboard". (d98d540e)
2018-02-13T00:05:51.2185665+11:00 0HLBI358JCCNE:00000003 [INF] Executed action "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" in 1338.452ms (afa2e885)
2018-02-13T00:05:51.2330977+11:00 0HLBI358JCCNE:00000003 [INF] Request finished in 1385.1455ms 302  (791a596a)
2018-02-13T00:05:51.2450720+11:00 0HLBI358JCCNE:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Home/Dashboard   (ca22a1cb)
2018-02-13T00:05:51.2572126+11:00 0HLBI358JCCNE:00000004 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:05:51.2662003+11:00 0HLBI358JCCNE:00000004 [INF] Executing action method "DOMS.WebApp.Controllers.HomeController.Dashboard (DOMS.WebApp)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:05:51.5042192+11:00 0HLBI358JCCNE:00000004 [INF] Executing ViewResult, running view at path "/Views/Home/Dashboard.cshtml". (9707eebe)
2018-02-13T00:05:52.3911244+11:00 0HLBI358JCCNE:00000004 [INF] Executed action "DOMS.WebApp.Controllers.HomeController.Dashboard (DOMS.WebApp)" in 1123.9633ms (afa2e885)
2018-02-13T00:05:52.4004036+11:00 0HLBI358JCCNE:00000004 [INF] Request finished in 1153.5973ms 200 text/html; charset=utf-8 (791a596a)
2018-02-13T00:05:55.3778523+11:00 0HLBI358JCCNE:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product   (ca22a1cb)
2018-02-13T00:05:55.3935512+11:00 0HLBI358JCCNE:00000005 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:05:55.4243614+11:00 0HLBI358JCCNE:00000005 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Index (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:05:55.4428096+11:00 0HLBI358JCCNE:00000005 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:05:55.5139278+11:00 0HLBI358JCCNE:00000005 [INF] Executed DbCommand ("5"ms) [Parameters=["@__userName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[ProductId], [x].[BrandId], [x].[CatalogueId], [x].[CreatedTime], [x].[CreatedUserId], [x].[CreatedUserName], [x].[CurrentCostAud], [x].[CurrentCostRmb], [x].[CurrentSellPriceAud], [x].[CurrentSellPriceRmb], [x].[Deleted], [x].[DeletedTime], [x].[Description], [x].[IsPublic], [x].[Labels], [x].[ProductName], [x].[UpdatedTime]
FROM [DOMS_Product] AS [x]
LEFT JOIN [AspNetUsers] AS [x.CreatedUser] ON [x].[CreatedUserId] = [x.CreatedUser].[Id]
WHERE [x.CreatedUser].[UserName] = @__userName_0" (0723d8ff)
2018-02-13T00:05:56.0323310+11:00 0HLBI358JCCNE:00000005 [INF] Executing ViewResult, running view at path "/Views/Product/Index.cshtml". (9707eebe)
2018-02-13T00:05:56.0942712+11:00 0HLBI358JCCNE:00000005 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Index (DOMS.WebApp)" in 674.0358ms (afa2e885)
2018-02-13T00:05:56.1090762+11:00 0HLBI358JCCNE:00000005 [INF] Request finished in 737.32ms 200 text/html; charset=utf-8 (791a596a)
2018-02-13T00:05:58.6554739+11:00 0HLBI358JCCNE:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product/Create   (ca22a1cb)
2018-02-13T00:05:58.6741184+11:00 0HLBI358JCCNE:00000006 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:05:58.7035300+11:00 0HLBI358JCCNE:00000006 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:05:58.8635803+11:00 0HLBI358JCCNE:00000006 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:05:58.8842515+11:00 0HLBI358JCCNE:00000006 [INF] Executed DbCommand ("1"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [d].[FamilyId], [d].[Memo], [d].[Name]
FROM [DOMS_Family] AS [d]" (0723d8ff)
2018-02-13T00:05:59.0810679+11:00 0HLBI358JCCNE:00000006 [INF] Executed DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[BrandId], [x].[BrandDescription], [x].[BrandLogo], [x].[BrandName], [x].[CountryId], [x].[CreatedTime], [x].[Deleted], [x].[DeletedTime], [x].[UpdatedTime], [x.Country].[CountryId], [x.Country].[CountryCode], [x.Country].[CountryName]
FROM [DOMS_Brand] AS [x]
INNER JOIN [DOMS_Country] AS [x.Country] ON [x].[CountryId] = [x.Country].[CountryId]
WHERE [x].[Deleted] = 0" (0723d8ff)
2018-02-13T00:05:59.7310753+11:00 0HLBI358JCCNE:00000006 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" in 1041.4688ms (afa2e885)
2018-02-13T00:05:59.8600030+11:00 0HLBI358JCCNE:00000006 [ERR] An unhandled exception has occurred while executing the request (cf926119)
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
lhbemde2.1iw(970,1826): error CS1031: Type expected
lhbemde2.1iw(970,2007): error CS1031: Type expected
lhbemde2.1iw(970,2188): error CS1031: Type expected
lhbemde2.1iw(970,1877): error CS1061: 'Product' does not contain a definition for 'FamilyId' and no extension method 'FamilyId' accepting a first argument of type 'Product' could be found (are you missing a using directive or an assembly reference?)
lhbemde2.1iw(970,2058): error CS1061: 'Product' does not contain a definition for 'FamilyId' and no extension method 'FamilyId' accepting a first argument of type 'Product' could be found (are you missing a using directive or an assembly reference?)
lhbemde2.1iw(970,2239): error CS1061: 'Product' does not contain a definition for 'FamilyId' and no extension method 'FamilyId' accepting a first argument of type 'Product' could be found (are you missing a using directive or an assembly reference?)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CreateCacheEntry(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-02-13T00:05:59.9305078+11:00 0HLBI358JCCNE:00000006 [INF] Request finished in 1281.4477ms 500 text/html; charset=utf-8 (791a596a)
2018-02-13T00:07:25.2351096+11:00 0HLBI358JCCNG:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product/Create   (ca22a1cb)
2018-02-13T00:07:25.2457250+11:00 0HLBI358JCCNG:00000001 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:07:25.2563802+11:00 0HLBI358JCCNG:00000001 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:07:25.2653008+11:00 0HLBI358JCCNG:00000001 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:07:25.2770281+11:00 0HLBI358JCCNG:00000001 [INF] Executed DbCommand ("1"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [d].[FamilyId], [d].[Memo], [d].[Name]
FROM [DOMS_Family] AS [d]" (0723d8ff)
2018-02-13T00:07:25.2932569+11:00 0HLBI358JCCNG:00000001 [INF] Executed DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[BrandId], [x].[BrandDescription], [x].[BrandLogo], [x].[BrandName], [x].[CountryId], [x].[CreatedTime], [x].[Deleted], [x].[DeletedTime], [x].[UpdatedTime], [x.Country].[CountryId], [x.Country].[CountryCode], [x.Country].[CountryName]
FROM [DOMS_Brand] AS [x]
INNER JOIN [DOMS_Country] AS [x.Country] ON [x].[CountryId] = [x.Country].[CountryId]
WHERE [x].[Deleted] = 0" (0723d8ff)
2018-02-13T00:07:25.7890901+11:00 0HLBI358JCCNG:00000001 [INF] Executing ViewResult, running view at path "/Views/Product/Create.cshtml". (9707eebe)
2018-02-13T00:07:26.3800311+11:00 0HLBI358JCCNG:00000001 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" in 1126.0635ms (afa2e885)
2018-02-13T00:07:26.4917313+11:00 0HLBI358JCCNG:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItemsWithValueField()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItems()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateGroupsAndOptions(String optionLabel, IEnumerable`1 selectList, ICollection`1 currentValues)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateGroupsAndOptions(String optionLabel, IEnumerable`1 selectList)
   at Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<<ExecuteAsync>b__19_0>d.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<GetChildContentAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<ExecuteAsync>d__19.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-02-13T00:07:26.6319056+11:00 0HLBI358JCCNG:00000001 [INF] Request finished in 1405.7757ms 500 text/html; charset=utf-8 (791a596a)
2018-02-13T00:07:26.6821979+11:00 0HLBI358JCCNG:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44388/favicon.ico   (ca22a1cb)
2018-02-13T00:07:26.6908351+11:00 0HLBI358JCCNG:00000002 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\Dean's\Practices\DOMS\DOMS.WebApp\wwwroot\favicon.ico"' (27b0a520)
2018-02-13T00:07:26.7347391+11:00 0HLBI358JCCNG:00000002 [INF] Request finished in 55.3497ms 200 image/x-icon (791a596a)
2018-02-13T00:07:49.2651703+11:00 0HLBI358JCCNG:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product/Create   (ca22a1cb)
2018-02-13T00:07:49.2723482+11:00 0HLBI358JCCNG:00000003 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:07:49.2810676+11:00 0HLBI358JCCNG:00000003 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:07:54.3288361+11:00 0HLBI358JCCNG:00000003 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:07:54.3381335+11:00 0HLBI358JCCNG:00000003 [INF] Executed DbCommand ("1"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [d].[FamilyId], [d].[Memo], [d].[Name]
FROM [DOMS_Family] AS [d]" (0723d8ff)
2018-02-13T00:08:06.1808953+11:00 0HLBI358JCCNG:00000003 [INF] Executed DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[BrandId], [x].[BrandDescription], [x].[BrandLogo], [x].[BrandName], [x].[CountryId], [x].[CreatedTime], [x].[Deleted], [x].[DeletedTime], [x].[UpdatedTime], [x.Country].[CountryId], [x.Country].[CountryCode], [x.Country].[CountryName]
FROM [DOMS_Brand] AS [x]
INNER JOIN [DOMS_Country] AS [x.Country] ON [x].[CountryId] = [x.Country].[CountryId]
WHERE [x].[Deleted] = 0" (0723d8ff)
2018-02-13T00:08:19.9279273+11:00 0HLBI358JCCNG:00000003 [INF] Executing ViewResult, running view at path "/Views/Product/Create.cshtml". (9707eebe)
2018-02-13T00:08:20.2129692+11:00 0HLBI358JCCNG:00000003 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" in 30930.3177ms (afa2e885)
2018-02-13T00:08:20.3473938+11:00 0HLBI358JCCNG:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItemsWithValueField()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItems()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateGroupsAndOptions(String optionLabel, IEnumerable`1 selectList, ICollection`1 currentValues)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateGroupsAndOptions(String optionLabel, IEnumerable`1 selectList)
   at Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<<ExecuteAsync>b__19_0>d.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<GetChildContentAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<ExecuteAsync>d__19.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-02-13T00:08:20.4808165+11:00 0HLBI358JCCNG:00000003 [INF] Request finished in 31216.2972ms 500 text/html; charset=utf-8 (791a596a)
2018-02-13T00:08:20.5113639+11:00 0HLBI358JCCNG:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:44388/favicon.ico   (ca22a1cb)
2018-02-13T00:08:20.5179681+11:00 0HLBI358JCCNG:00000004 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\Dean's\Practices\DOMS\DOMS.WebApp\wwwroot\favicon.ico"' (27b0a520)
2018-02-13T00:08:20.5274714+11:00 0HLBI358JCCNG:00000004 [INF] Request finished in 16.2117ms 200 image/x-icon (791a596a)
2018-02-13T00:08:31.5158684+11:00 0HLBI358JCCNG:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product/Create   (ca22a1cb)
2018-02-13T00:08:31.5332140+11:00 0HLBI358JCCNG:00000005 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:08:31.5448763+11:00 0HLBI358JCCNG:00000005 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:08:34.2168431+11:00 0HLBI358JCCNG:00000005 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:08:34.2731430+11:00 0HLBI358JCCNG:00000005 [INF] Executed DbCommand ("0"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [d].[FamilyId], [d].[Memo], [d].[Name]
FROM [DOMS_Family] AS [d]" (0723d8ff)
2018-02-13T00:08:34.2847741+11:00 0HLBI358JCCNG:00000005 [INF] Executed DbCommand ("0"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[BrandId], [x].[BrandDescription], [x].[BrandLogo], [x].[BrandName], [x].[CountryId], [x].[CreatedTime], [x].[Deleted], [x].[DeletedTime], [x].[UpdatedTime], [x.Country].[CountryId], [x.Country].[CountryCode], [x.Country].[CountryName]
FROM [DOMS_Brand] AS [x]
INNER JOIN [DOMS_Country] AS [x.Country] ON [x].[CountryId] = [x.Country].[CountryId]
WHERE [x].[Deleted] = 0" (0723d8ff)
2018-02-13T00:08:34.8178681+11:00 0HLBI358JCCNG:00000005 [INF] Executing ViewResult, running view at path "/Views/Product/Create.cshtml". (9707eebe)
2018-02-13T00:08:35.1162486+11:00 0HLBI358JCCNG:00000005 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" in 3576.4014ms (afa2e885)
2018-02-13T00:08:35.1884311+11:00 0HLBI358JCCNG:00000005 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.ArgumentNullException: Value cannot be null.
Parameter name: items
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList..ctor(IEnumerable items, String dataValueField, String dataTextField, IEnumerable selectedValues, String dataGroupField)
   at Microsoft.AspNetCore.Mvc.Rendering.SelectList..ctor(IEnumerable items, String dataValueField, String dataTextField, Object selectedValue)
   at Microsoft.AspNetCore.Mvc.Rendering.SelectList..ctor(IEnumerable items, String dataValueField, String dataTextField)
   at CallSite.Target(Closure , CallSite , Type , Object , String , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at AspNetCore._Views_Product_Create_cshtml.<<ExecuteAsync>b__19_0>d.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<GetChildContentAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<ExecuteAsync>d__19.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-02-13T00:08:35.3021569+11:00 0HLBI358JCCNG:00000005 [INF] Request finished in 3793.8258ms 500 text/html; charset=utf-8 (791a596a)
2018-02-13T00:08:35.3253173+11:00 0HLBI358JCCNG:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:44388/favicon.ico   (ca22a1cb)
2018-02-13T00:08:35.3405738+11:00 0HLBI358JCCNG:00000006 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\Dean's\Practices\DOMS\DOMS.WebApp\wwwroot\favicon.ico"' (27b0a520)
2018-02-13T00:08:35.3667195+11:00 0HLBI358JCCNG:00000006 [INF] Request finished in 36.5084ms 200 image/x-icon (791a596a)
2018-02-13T00:14:36.6711855+11:00 0HLBI3A8B6FKP:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44388/   (ca22a1cb)
2018-02-13T00:14:36.9526166+11:00 0HLBI3A8B6FKP:00000001 [INF] Executing action method "DOMS.WebApp.Controllers.HomeController.Index (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:14:36.9734103+11:00 0HLBI3A8B6FKP:00000001 [INF] Executing RedirectResult, redirecting to "/Account/Login". (d98d540e)
2018-02-13T00:14:36.9860183+11:00 0HLBI3A8B6FKP:00000001 [INF] Executed action "DOMS.WebApp.Controllers.HomeController.Index (DOMS.WebApp)" in 60.6064ms (afa2e885)
2018-02-13T00:14:37.0258801+11:00 0HLBI3A8B6FKP:00000001 [INF] Request finished in 388.4107ms 302  (791a596a)
2018-02-13T00:14:37.0653772+11:00 0HLBI3A8B6FKP:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Account/Login   (ca22a1cb)
2018-02-13T00:14:37.2456172+11:00 0HLBI3A8B6FKP:00000002 [INF] Executing action method "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:14:37.2584606+11:00 0HLBI3A8B6FKP:00000002 [INF] AuthenticationScheme: "Identity.External" signed out. (d3f50c8d)
2018-02-13T00:14:41.7469418+11:00 0HLBI3A8B6FKP:00000002 [INF] Executing ViewResult, running view at path "/Views/Account/Login.cshtml". (9707eebe)
2018-02-13T00:14:42.0871107+11:00 0HLBI3A8B6FKP:00000002 [INF] Executed action "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" in 4965.4806ms (afa2e885)
2018-02-13T00:14:42.1053705+11:00 0HLBI3A8B6FKP:00000002 [INF] Request finished in 5052.2204ms 200 text/html; charset=utf-8 (791a596a)
2018-02-13T00:14:44.5349084+11:00 0HLBI3A8B6FKP:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44388/Account/Login application/x-www-form-urlencoded 246 (ca22a1cb)
2018-02-13T00:14:44.6472846+11:00 0HLBI3A8B6FKP:00000003 [INF] Executing action method "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" with arguments (["DOMS.Model.ViewModels.AccountViewModels.LoginViewModel", ""]) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:14:44.9064192+11:00 0HLBI3A8B6FKP:00000003 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:14:45.2616433+11:00 0HLBI3A8B6FKP:00000003 [INF] Executed DbCommand ("64"ms) [Parameters=["@__normalizedUserName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[Email], [u].[EmailConfirmed], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0" (0723d8ff)
2018-02-13T00:14:45.4179136+11:00 0HLBI3A8B6FKP:00000003 [INF] Executed DbCommand ("3"ms) [Parameters=["@__user_Id_0='?' (Size = 450)"], CommandType='Text', CommandTimeout='30']"
""SELECT [uc].[Id], [uc].[ClaimType], [uc].[ClaimValue], [uc].[UserId]
FROM [AspNetUserClaims] AS [uc]
WHERE [uc].[UserId] = @__user_Id_0" (0723d8ff)
2018-02-13T00:14:45.5160660+11:00 0HLBI3A8B6FKP:00000003 [INF] Executed DbCommand ("5"ms) [Parameters=["@__userId_0='?' (Size = 450)"], CommandType='Text', CommandTimeout='30']"
""SELECT [role].[Name]
FROM [AspNetUserRoles] AS [userRole]
INNER JOIN [AspNetRoles] AS [role] ON [userRole].[RoleId] = [role].[Id]
WHERE [userRole].[UserId] = @__userId_0" (0723d8ff)
2018-02-13T00:14:45.5309033+11:00 0HLBI3A8B6FKP:00000003 [INF] AuthenticationScheme: "Identity.Application" signed in. (c66dd7e7)
2018-02-13T00:14:45.5384656+11:00 0HLBI3A8B6FKP:00000003 [INF] User logged in. (fdce0db4)
2018-02-13T00:14:45.5503067+11:00 0HLBI3A8B6FKP:00000003 [INF] Executing RedirectResult, redirecting to "/Home/Dashboard". (d98d540e)
2018-02-13T00:14:45.5568739+11:00 0HLBI3A8B6FKP:00000003 [INF] Executed action "DOMS.WebApp.Controllers.AccountController.Login (DOMS.WebApp)" in 997.8275ms (afa2e885)
2018-02-13T00:14:45.5670412+11:00 0HLBI3A8B6FKP:00000003 [INF] Request finished in 1037.3554ms 302  (791a596a)
2018-02-13T00:14:45.5785261+11:00 0HLBI3A8B6FKP:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Home/Dashboard   (ca22a1cb)
2018-02-13T00:14:45.6102543+11:00 0HLBI3A8B6FKP:00000004 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:14:45.6192036+11:00 0HLBI3A8B6FKP:00000004 [INF] Executing action method "DOMS.WebApp.Controllers.HomeController.Dashboard (DOMS.WebApp)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:14:45.8943975+11:00 0HLBI3A8B6FKP:00000004 [INF] Executing ViewResult, running view at path "/Views/Home/Dashboard.cshtml". (9707eebe)
2018-02-13T00:14:46.6551752+11:00 0HLBI3A8B6FKP:00000004 [INF] Executed action "DOMS.WebApp.Controllers.HomeController.Dashboard (DOMS.WebApp)" in 1037.1073ms (afa2e885)
2018-02-13T00:14:46.6610975+11:00 0HLBI3A8B6FKP:00000004 [INF] Request finished in 1084.533ms 200 text/html; charset=utf-8 (791a596a)
2018-02-13T00:14:48.4736789+11:00 0HLBI3A8B6FKP:00000005 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product   (ca22a1cb)
2018-02-13T00:14:48.4845123+11:00 0HLBI3A8B6FKP:00000005 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:14:48.5076092+11:00 0HLBI3A8B6FKP:00000005 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Index (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:14:48.5287992+11:00 0HLBI3A8B6FKP:00000005 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:14:48.5833644+11:00 0HLBI3A8B6FKP:00000005 [INF] Executed DbCommand ("3"ms) [Parameters=["@__userName_0='?' (Size = 256)"], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[ProductId], [x].[BrandId], [x].[CatalogueId], [x].[CreatedTime], [x].[CreatedUserId], [x].[CreatedUserName], [x].[CurrentCostAud], [x].[CurrentCostRmb], [x].[CurrentSellPriceAud], [x].[CurrentSellPriceRmb], [x].[Deleted], [x].[DeletedTime], [x].[Description], [x].[IsPublic], [x].[Labels], [x].[ProductName], [x].[UpdatedTime]
FROM [DOMS_Product] AS [x]
LEFT JOIN [AspNetUsers] AS [x.CreatedUser] ON [x].[CreatedUserId] = [x.CreatedUser].[Id]
WHERE [x.CreatedUser].[UserName] = @__userName_0" (0723d8ff)
2018-02-13T00:14:48.9069692+11:00 0HLBI3A8B6FKP:00000005 [INF] Executing ViewResult, running view at path "/Views/Product/Index.cshtml". (9707eebe)
2018-02-13T00:14:48.9558850+11:00 0HLBI3A8B6FKP:00000005 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Index (DOMS.WebApp)" in 463.4741ms (afa2e885)
2018-02-13T00:14:48.9620329+11:00 0HLBI3A8B6FKP:00000005 [INF] Request finished in 493.9792ms 200 text/html; charset=utf-8 (791a596a)
2018-02-13T00:14:50.6690644+11:00 0HLBI3A8B6FKP:00000006 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product/Create   (ca22a1cb)
2018-02-13T00:14:50.6802557+11:00 0HLBI3A8B6FKP:00000006 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:14:50.6942607+11:00 0HLBI3A8B6FKP:00000006 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:14:53.1168408+11:00 0HLBI3A8B6FKP:00000006 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:14:53.1316950+11:00 0HLBI3A8B6FKP:00000006 [INF] Executed DbCommand ("1"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [d].[FamilyId], [d].[Memo], [d].[Name]
FROM [DOMS_Family] AS [d]" (0723d8ff)
2018-02-13T00:14:53.3812945+11:00 0HLBI3A8B6FKP:00000006 [INF] Executed DbCommand ("2"ms) [Parameters=["@__familyId_0='?'"], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[CatalogueId], [x].[FamilyId], [x].[Memo], [x].[Name], [x.Family].[FamilyId], [x.Family].[Memo], [x.Family].[Name]
FROM [DOMS_Catalogue] AS [x]
INNER JOIN [DOMS_Family] AS [x.Family] ON [x].[FamilyId] = [x.Family].[FamilyId]
WHERE [x].[FamilyId] = @__familyId_0
ORDER BY [x].[FamilyId]" (0723d8ff)
2018-02-13T00:14:53.4439830+11:00 0HLBI3A8B6FKP:00000006 [INF] Executed DbCommand ("2"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[BrandId], [x].[BrandDescription], [x].[BrandLogo], [x].[BrandName], [x].[CountryId], [x].[CreatedTime], [x].[Deleted], [x].[DeletedTime], [x].[UpdatedTime], [x.Country].[CountryId], [x.Country].[CountryCode], [x.Country].[CountryName]
FROM [DOMS_Brand] AS [x]
INNER JOIN [DOMS_Country] AS [x.Country] ON [x].[CountryId] = [x.Country].[CountryId]
WHERE [x].[Deleted] = 0" (0723d8ff)
2018-02-13T00:14:54.1599657+11:00 0HLBI3A8B6FKP:00000006 [INF] Executing ViewResult, running view at path "/Views/Product/Create.cshtml". (9707eebe)
2018-02-13T00:14:54.4484175+11:00 0HLBI3A8B6FKP:00000006 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" in 3760.1534ms (afa2e885)
2018-02-13T00:14:54.5625810+11:00 0HLBI3A8B6FKP:00000006 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItemsWithValueField()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItems()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateGroupsAndOptions(String optionLabel, IEnumerable`1 selectList, ICollection`1 currentValues)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateSelect(ViewContext viewContext, ModelExplorer modelExplorer, String optionLabel, String expression, IEnumerable`1 selectList, ICollection`1 currentValues, Boolean allowMultiple, Object htmlAttributes)
   at Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<<ExecuteAsync>b__19_0>d.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<GetChildContentAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<ExecuteAsync>d__19.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-02-13T00:14:54.7224570+11:00 0HLBI3A8B6FKP:00000006 [INF] Request finished in 4057.8197ms 500 text/html; charset=utf-8 (791a596a)
2018-02-13T00:15:01.7641222+11:00 0HLBI3A8B6FKP:00000007 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product/Create   (ca22a1cb)
2018-02-13T00:15:01.7791231+11:00 0HLBI3A8B6FKP:00000007 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:15:01.7894192+11:00 0HLBI3A8B6FKP:00000007 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:15:04.0867370+11:00 0HLBI3A8B6FKP:00000007 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:15:04.0981227+11:00 0HLBI3A8B6FKP:00000007 [INF] Executed DbCommand ("0"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [d].[FamilyId], [d].[Memo], [d].[Name]
FROM [DOMS_Family] AS [d]" (0723d8ff)
2018-02-13T00:15:12.7378246+11:00 0HLBI3A8B6FKP:00000007 [INF] Executed DbCommand ("0"ms) [Parameters=["@__familyId_0='?'"], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[CatalogueId], [x].[FamilyId], [x].[Memo], [x].[Name], [x.Family].[FamilyId], [x.Family].[Memo], [x.Family].[Name]
FROM [DOMS_Catalogue] AS [x]
INNER JOIN [DOMS_Family] AS [x.Family] ON [x].[FamilyId] = [x.Family].[FamilyId]
WHERE [x].[FamilyId] = @__familyId_0
ORDER BY [x].[FamilyId]" (0723d8ff)
2018-02-13T00:15:24.2150813+11:00 0HLBI3A8B6FKP:00000007 [INF] Executed DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[BrandId], [x].[BrandDescription], [x].[BrandLogo], [x].[BrandName], [x].[CountryId], [x].[CreatedTime], [x].[Deleted], [x].[DeletedTime], [x].[UpdatedTime], [x.Country].[CountryId], [x.Country].[CountryCode], [x.Country].[CountryName]
FROM [DOMS_Brand] AS [x]
INNER JOIN [DOMS_Country] AS [x.Country] ON [x].[CountryId] = [x.Country].[CountryId]
WHERE [x].[Deleted] = 0" (0723d8ff)
2018-02-13T00:15:27.9713868+11:00 0HLBI3A8B6FKP:00000007 [INF] Executing ViewResult, running view at path "/Views/Product/Create.cshtml". (9707eebe)
2018-02-13T00:15:28.2125793+11:00 0HLBI3A8B6FKP:00000007 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" in 26397.5347ms (afa2e885)
2018-02-13T00:15:28.3662138+11:00 0HLBI3A8B6FKP:00000007 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItemsWithValueField()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetListItems()
   at Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateGroupsAndOptions(String optionLabel, IEnumerable`1 selectList, ICollection`1 currentValues)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateSelect(ViewContext viewContext, ModelExplorer modelExplorer, String optionLabel, String expression, IEnumerable`1 selectList, ICollection`1 currentValues, Boolean allowMultiple, Object htmlAttributes)
   at Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<<ExecuteAsync>b__19_0>d.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<GetChildContentAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetCore._Views_Product_Create_cshtml.<ExecuteAsync>d__19.MoveNext() in D:\Dean's\Practices\DOMS\DOMS.WebApp\Views\Product\Create.cshtml:line 4
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-02-13T00:15:28.4973965+11:00 0HLBI3A8B6FKP:00000007 [INF] Request finished in 26749.5658ms 500 text/html; charset=utf-8 (791a596a)
2018-02-13T00:15:28.5445906+11:00 0HLBI3A8B6FKP:00000008 [INF] Request starting HTTP/1.1 GET http://localhost:44388/favicon.ico   (ca22a1cb)
2018-02-13T00:15:28.5555374+11:00 0HLBI3A8B6FKP:00000008 [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\Dean's\Practices\DOMS\DOMS.WebApp\wwwroot\favicon.ico"' (27b0a520)
2018-02-13T00:15:28.5629184+11:00 0HLBI3A8B6FKP:00000008 [INF] Request finished in 19.6021ms 200 image/x-icon (791a596a)
2018-02-13T00:15:42.7792432+11:00 0HLBI3A8B6FKP:00000009 [INF] Request starting HTTP/1.1 GET http://localhost:44388/Product/Create   (ca22a1cb)
2018-02-13T00:15:42.7958979+11:00 0HLBI3A8B6FKP:00000009 [INF] AuthenticationScheme: "Identity.Application" was successfully authenticated. (1805f3b3)
2018-02-13T00:15:42.8134082+11:00 0HLBI3A8B6FKP:00000009 [INF] Executing action method "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-02-13T00:15:44.6249253+11:00 0HLBI3A8B6FKP:00000009 [INF] Entity Framework Core "2.0.1-rtm-125" initialized '"ApplicationDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-02-13T00:15:44.6473032+11:00 0HLBI3A8B6FKP:00000009 [INF] Executed DbCommand ("5"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [d].[FamilyId], [d].[Memo], [d].[Name]
FROM [DOMS_Family] AS [d]" (0723d8ff)
2018-02-13T00:15:44.6615958+11:00 0HLBI3A8B6FKP:00000009 [INF] Executed DbCommand ("4"ms) [Parameters=["@__familyId_0='?'"], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[CatalogueId], [x].[FamilyId], [x].[Memo], [x].[Name], [x.Family].[FamilyId], [x.Family].[Memo], [x.Family].[Name]
FROM [DOMS_Catalogue] AS [x]
INNER JOIN [DOMS_Family] AS [x.Family] ON [x].[FamilyId] = [x.Family].[FamilyId]
WHERE [x].[FamilyId] = @__familyId_0
ORDER BY [x].[FamilyId]" (0723d8ff)
2018-02-13T00:15:44.6750781+11:00 0HLBI3A8B6FKP:00000009 [INF] Executed DbCommand ("6"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""SELECT [x].[BrandId], [x].[BrandDescription], [x].[BrandLogo], [x].[BrandName], [x].[CountryId], [x].[CreatedTime], [x].[Deleted], [x].[DeletedTime], [x].[UpdatedTime], [x.Country].[CountryId], [x.Country].[CountryCode], [x.Country].[CountryName]
FROM [DOMS_Brand] AS [x]
INNER JOIN [DOMS_Country] AS [x.Country] ON [x].[CountryId] = [x.Country].[CountryId]
WHERE [x].[Deleted] = 0" (0723d8ff)
2018-02-13T00:15:44.9607734+11:00 0HLBI3A8B6FKP:00000009 [INF] Executing ViewResult, running view at path "/Views/Product/Create.cshtml". (9707eebe)
2018-02-13T00:15:45.1099133+11:00 0HLBI3A8B6FKP:00000009 [INF] Executed action "DOMS.WebApp.Controllers.ProductController.Create (DOMS.WebApp)" in 2307.8007ms (afa2e885)
2018-02-13T00:15:45.1158136+11:00 0HLBI3A8B6FKP:00000009 [INF] Request finished in 2346.0044ms 200 text/html; charset=utf-8 (791a596a)
2018-02-13T00:15:45.3360963+11:00 0HLBI3A8B6FKP:0000000A [INF] Request starting HTTP/1.1 GET http://localhost:44388/favicon.ico   (ca22a1cb)
2018-02-13T00:15:45.3430237+11:00 0HLBI3A8B6FKP:0000000A [INF] Sending file. Request path: '"/favicon.ico"'. Physical path: '"D:\Dean's\Practices\DOMS\DOMS.WebApp\wwwroot\favicon.ico"' (27b0a520)
2018-02-13T00:15:45.3629360+11:00 0HLBI3A8B6FKP:0000000A [INF] Request finished in 24.9734ms 200 image/x-icon (791a596a)
